### ISSUE TITLE
The abbreviated "g" command line switch does not work

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#10]
The following does not work
`code-generator g ...`
The following does work
`code-generator --generate`

Please fix

**Comment by vsuaste** [comment]
I was experimenting some issues with this commands when I tried to use the global command. But it was because a really old version of code-generator was installed globally. I uninstalled the global package and intall it again with the code of this repository (master branch) and everything works perfectly. Maybe this issue has something to do with your case.

**Comment by asishallab** [comment]
@vsuaste the problem definitively has nothing to do with my local installation, because I tried using the generator on a brand new server where not even node was installed before.
