### ISSUE TITLE
No output is generated

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#11]
Consider the following input file `./doc/transcript_count.json`
```
{
  "model" : "TranscriptCount",
  "storageType" : "SQL",
  "attributes" : {
    "gene" : "String",
    "variable" : "String",
    "count" : "Double",
    "tissue_or_condition": "String",
    "individual_id": "Integer"
  }
}
```

Invoking `code-generator --generate ./doc/transcript_count.json .` does not give an error, but also does _not_ generate any output file.

**Comment by asishallab** [comment]
The bug remains when the code-generator is invoked with 
`code-generator --generate ./doc .`

**Comment by vsuaste** [comment]
In order to generate the code we need to run the command `code-generator generate ./doc .`
A better and updated README contains the proper guide.

Just a couple of comments here : 
1.- Graphql types are String, Float, Boolean, Int. I left only these as options for the attributes types. So, the transcript_count.json should be:
```
{
  "model" : "TranscriptCount",
  "storageType" : "SQL",
  "attributes" : {
    "gene" : "String",
    "variable" : "String",
    "count" : "Float",
    "tissue_or_condition": "String",
    "individual_id": "Int"
  }
}
```
2.- Also, for the name of the model in some parts of the code we use _pluralize_. In this case that the model is a composed word I would assume it shouldn't be a problem and the __pluralize__ function will only add a _'s'_, but tests have not been done with composed words as the name of the model.

**Comment by vsuaste** [comment]
The README file has been updated with information about how to use the code-generator.  Hopefully is now clear and you will be able to run it with your test.
